version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Build wheel package
          command: ./setup.py bdist_wheel
      - persist_to_workspace:
          root: .
          paths: ./dist/*.whl
  test-py38: &test-py38
    docker:
      - image: mauvilsa/narchi-test:2020.05.21-py38
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run unit tests
          command: |
            py=$(python3 --version | sed -r 's|.* 3\.([0-9]+)\..*|3.\1|')
            pip3 install --user $(ls ./dist/*.whl)[test]
            python3 -m narchi_tests coverage xml coverage_py$py.xml
      - persist_to_workspace:
          root: .
          paths:
            - ./coverage_*.xml
  #test-py37:
  #  <<: *test-py38
  #  docker:
  #    - image: mauvilsa/narchi-test:2020.05.21-py37
  #test-py36:
  #  <<: *test-py38
  #  docker:
  #    - image: mauvilsa/narchi-test:2020.05.21-py36
  codecov:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Code coverage
          command: |
            mv coverage_py3.8.xml coverage.xml
            rm -f coverage_*.xml
            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN_NARCHI
  publish-pypi:
    docker:
      - image: mauvilsa/docker-twine:1.11.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish Release on PyPI
          command: twine upload --username "${PYPI_USER}" --password "${PYPI_PASS}" ./dist/*.whl

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build: &buildreq
          filters: &tagfilter
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - test-py38: &testreq
          <<: *buildreq
          requires:
            - build
      #- test-py37:
      #    <<: *testreq
      #- test-py36:
      #    <<: *testreq
      - codecov:
          requires:
            - test-py38
      - publish-pypi:
          filters:
            branches:
              ignore: /.*/
            <<: *tagfilter
          context: pypi-upload-context
          requires:
            - test-py38
            #- test-py37
            #- test-py36
            - codecov
