version: 2.1

jobs:
  build:
    docker:
      - image: mauvilsa/narchi-test:2020.01.21-py38
    steps:
      - checkout
      - run:
          name: Build wheel package
          command: ./setup.py bdist_wheel
      - persist_to_workspace:
          root: .
          paths: ./dist/*.whl
  test-py38: &test-py38
    docker:
      - image: mauvilsa/narchi-test:2020.01.21-py38
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run unit tests
          command: |
            py=$(python3 --version | sed -r 's|.* 3\.([0-9]+)\..*|3.\1|')
            pip3 install --user $(ls ./dist/*.whl)[test]
            python3 -m narchi_tests coverage xml coverage_$py.xml
      - persist_to_workspace:
          root: .
          paths: ./coverage_*.xml
  test-py37:
    <<: *test-py38
    docker:
      - image: mauvilsa/narchi-test:2020.01.21-py37
  test-py36:
    <<: *test-py38
    docker:
      - image: mauvilsa/narchi-test:2020.01.21-py36
  #sonarcloud:
  #  docker:
  #    - image: mauvilsa/narchi-test:2020.01.21-py38
  #  steps:
  #    - attach_workspace:
  #        at: .
  #    - run:
  #        name: Sonarcloud
  #        command: mv coverage_3.8.xml coverage.xml
  #    - sonarcloud/scan
  publish-pypi:
    docker:
      - image: mauvilsa/docker-twine:1.11.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish Release on PyPI
          command: twine upload --username "${PYPI_USER}" --password "${PYPI_PASS}" ./dist/*.whl

#orbs:
#  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build: &buildreq
          filters: &tagfilter
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - test-py38: &testreq
          <<: *buildreq
          requires:
            - build
      - test-py37:
          <<: *testreq
      - test-py36:
          <<: *testreq
      #- sonarcloud:
      #    context: SonarCloud
      #    requires:
      #      - test-py38
      - publish-pypi:
          filters:
            branches:
              ignore: /.*/
            <<: *tagfilter
          context: pypi-upload-context
          requires:
            - test-py38
            - test-py37
            - test-py36
            #- sonarcloud
